### ISSUE TITLE
ESP32 as FCS - ESC's (blheli32) 

### ISSUE THREAD

**Issue by europer** [JyeSmith/dshot-esc-tester#5]
Hi, 
new into drones regards programming and in my project (homematic what is lot easier programming then drones) I use only esp32 since they are great and cheap and like to program with them.
Then I wanted to start with a new project and this is to make a drone controlled with esp32 as master of desaster ;) I fast did see that esp32 is not the prefered mc and most ESC now use Dshot150-1200, singleshot, multishot and not what I did see the classic old PWM as I was used to in other project (where speed and etc etc was perhaps not so importand and small deviation due to noice into the analog signal) 
So sorry for my perhaps dum/bold questions since I see this is the bottleneck for me in the consept phase is to controll the ESC with the ESP32 (as FS). So here my questions:

1. you have made a Dshot600 protocoll for esp32?
2. since the esp32 use 3.3v gpio but I mean the input for the ESC are 5v how to you overcome this issue?
3. is ist possible with the esp32 to have 4 x the protocoll (dshot600) to controll the ESC for again to controll the 4 motors?
4. is your protocoll also without need of calibration what should be one of the advantage of the dshot?
5. do your protocoll also give a check sum to controll that right data was transmitted?

reason for my questions is as I did statet above is to make my own FS with esp32 but implemtent the new protocoll dshot for controlling the ESC what can use this protocoll => programming FS for a drone with esp32

thanks and happy weekend
europer

**Comment by JyeSmith** [comment]
Hi @europer 

Just in case you havent found it, did you look at the Betaflight firmware?  A lot more work has been done with stm32 MCUs.

>     1. you have made a Dshot600 protocoll for esp32?

DS150 and 300 are also perfectly fine.  Do not get too hung up with using the absolutely fastest protocol.

https://github.com/JyeSmith/dshot-esc-tester/blob/8695f27fb705892a0906acddc60b4a4e8dfb21a3/dshot-esc-tester.ino#L413

>     2. since the esp32 use 3.3v gpio but I mean the input for the ESC are 5v how to you overcome this issue?

This is not a problem.  MCUs on ESCs are happy with3.3V signal.

>     3. is ist possible with the esp32 to have 4 x the protocoll (dshot600) to controll the ESC for again to controll the 4 motors?

I am not sure and never looked that far.

>     4. is your protocoll also without need of calibration what should be one of the advantage of the dshot?

Correct. DShot does not require any calibration since it is a digital signal.

>     5. do your protocoll also give a check sum to controll that right data was transmitted?

https://github.com/JyeSmith/dshot-esc-tester/blob/8695f27fb705892a0906acddc60b4a4e8dfb21a3/dshot-esc-tester.ino#L403

**Comment by europer** [comment]
Thanks for the answer 👍 good job.
